### ISSUE TITLE
Refactor extraction

### ISSUE THREAD

**Issue by haz** [AI-Planning/macq#125]
## Tasks
- [ ] Create subfolders, `methods` and `model`, inside of the `macq/extract` folder.
- [ ] `model.py` and `learned_*` can move to `model`; methods move to `methods`; `extract.py` stays put
  - For now, keep the imports in `extract/__init__.py` flat (so this is just moving around the files)
- [ ] Shift `to_pddl` methods to the `Learned*` objects. If `f` is a `LearnedFluent`, then `f.to_pddl()` should return a `pddl` fluent.
- [ ] The `model.py::to_pddl` method should recursively call the appropriate things on `LearnedAction` and `LearnedFluent` objects. This will improve over time, as the complexity of `Model` changes.
- [ ] Use the most general form of `pddl` that the representation allows (so parameters, objects, types, etc, if available).

## Notes
- Depends on #124
